gitted-client: checks about unpriviledged LXC settings

diff --git a/tree/usr/bin/gitted-client b/tree/usr/bin/gitted-client
--- a/tree/usr/bin/gitted-client
+++ b/tree/usr/bin/gitted-client
@@ -235,9 +235,48 @@ gitted_check_env() {
         echo "sudo apt-get install lxc" >&2
         exit 3
     fi
-    if [ $(id -u) -ne 0 ]; then
+    if [ $(id -u) -eq 0 ]; then
+        nef_log "RUNNING AS ROOT! Notice: you can work as an unpriviledged user as well."
+    else
         user_name=$(id -un)
+        group_name=$(id -gn)
+        error=
+        if ! grep -q "^${user_name}:" /etc/subuid; then
+            error="User '$user_name' misses an entry in /etc/subuid"
+        elif ! grep -q "^${group_name}:" /etc/subgid; then
+            error="User '$user_name' misses an entry in /etc/subuid"
+        elif ! [ -f ~/.config/lxc/default.conf ]; then
+            error="Missing file '~/.config/lxc/default.conf' with 'id_map' declarations"
+        fi
 
+        if [ -n "$error" ]; then
+            nef_log "Error: $error"
+            nef_log "There are 4 files you need to update for LXC to run properly"
+            nef_log "as unpriviledged user '$user_name'."
+            nef_log ""
+            nef_log "You can fix them automatically with the commands below:"
+        cat <<MEOF >&2
+# START
+
+grep "^${user_name}:" /etc/subuid || sudo -c 'echo "${user_name}:100000:65536" >>/etc/subuid'
+grep "^${group_name}:" /etc/subgid || sudo -c 'echo "${group_name}:100000:65536" >>/etc/subgid'
+grep "^${user_name} " /etc/lxc/lxc-usernet || sudo -c 'echo "${user_name} veth lxcbr0 10" >>/etc/lxc/lxc-usernet'
+
+[ -f ~/.config/lxc/default.conf ] || cat <<EOF >~/.config/lxc/default.conf
+lxc.network.type = veth
+lxc.network.link = lxcbr0
+lxc.network.flags = up
+lxc.network.hwaddr = 00:16:3e:xx:xx:xx
+lxc.id_map = u 0 100000 65536
+lxc.id_map = g 0 100000 65536
+EOF
+
+# END
+MEOF
+        nef_log "Hint: select the lines between #START and #END (with the mouse), "
+        nef_log "then click with the middle button to paste it."
+        exit 3
+        fi
     fi
 
 }
